services:
  db:
    image: postgres:18-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=sunjinlee"
    volumes:
      - db-volume:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - wod-local-network
  redis:
    image: redis/redis-stack-server:7.4.0-v8
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - wod-local-network
  worker:
    build:
      context: .
      dockerfile: Dockerfile_worker
    env_file:
      - .env.docker
    volumes:
      - ./tmp:/app/tmp
    networks:
      - wod-local-network
    depends_on:
      - db
      - redis
  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    ports:
      - 8088:8088
    env_file:
      - .env.docker
    volumes:
      - ./tmp:/app/tmp
    networks:
      - wod-local-network
    depends_on:
      - db
      - redis

networks:
  wod-local-network:
    name: wod-local-network
    driver: bridge

volumes:
  db-volume:
  redis-data:
