services:
  db:
    image: postgres:18-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_USER=sunjinlee"
    volumes:
      - db-volume:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - local-network
  redis:
    image: redis/redis-stack-server:7.4.0-v8
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

networks:
  local-network:
    name: local-network
    driver: bridge

volumes:
  db-volume:
  redis-data: